;
; AVRBlink.asm
;
; Created: 08/02/2019 22:08:45
; Author : Mark
;

.include "./m328Pdef.inc"
.org 0x00
rjmp start

start:
	;Store B11111111 in r16, then write to PORTD
	ldi r16, 0b11111111 
	out DDRD, r16
	;Load r16 with B00000000 and write to PORTD 

	Toggle:
	RCALL Delay
	out PORTD, r16
	com r16
   rjmp Toggle

Delay:
; Generated by delay loop calculator
; at http://www.bretmulvey.com/avrdelay.html
;
; Delay 8 000 000 cycles
; 500ms at 16 MHz

    ldi  r18, 41
    ldi  r19, 150
    ldi  r20, 128
L1: dec  r20
    brne L1
    dec  r19
    brne L1
    dec  r18
    brne L1

RET

.EXIT
